### ISSUE TITLE
SheetStops shared instance between all BottomSheet

### ISSUE THREAD

**Issue by Migoked** [TheEightBot/MauiDrawer#2]
The default value of SheetStopsProperty create a single instance of the list. Which means every sheetstop you declare in your Bottomsheets will be added to this single instance. 

I had to use defaultValueCreator to fix it : 

```
public static BindableProperty SheetStopsProperty =
        BindableProperty.Create(
            nameof(SheetStops),
            typeof(List<SheetStop>),
            typeof(BottomSheet),
            defaultValueCreator: bindable => new List<SheetStop>());
```

Btw thx for sharing this component its pretty nice to use 👍

**Comment by michaelstonis** [comment]
This has been resolved with PR https://github.com/TheEightBot/WhatIsThisSheet/pull/3
